name: Docker Image and Update k8s Config CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker:
    runs-on: ubuntu-latest
    outputs:
      image-version: ${{ steps.getversion.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat docker/VERSION)"
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag andrestless/dummy-web-app:latest
    - name: Tag with version tag
      run: docker image tag andrestless/dummy-web-app:latest andrestless/dummy-web-app:${{ steps.getversion.outputs.version }}
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Push image
      run: docker image push --all-tags andrestless/dummy-web-app

  git-push:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Clone repository
      run: git clone git@github.com:Obiuzera/hackday.git
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    - name: patch file
      run: |
        cd hackday/web-app && \
          cp web-app-deployment.yaml temp.yaml && \
          kubectl patch --local -f temp.yaml \
          -p '{"spec":{"template":{"spec":{"containers":[{"name":"web-app","image":"andrestless/dummy-web-app:${{ steps.getversion.outputs.version }}"}]}}}}' -o yaml \
          > web-app-deployment.yaml && \
          rm temp.yaml
    - name: git add
      run: cd hackday && git add web-app/web-app-deployment.yaml && git commit -m "Update web-app deployment image to ${{ steps.getversion.outputs.version }}"
    - name: git push
      run: cd hackday && git push
