name: Docker Image and Update k8s Config CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag andrestless/dummy-web-app:latest
    - name: Tag with version tag
      run: docker image tag andrestless/dummy-web-app:latest andrestless/dummy-web-app:${{ steps.getversion.outputs.version }}
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Push image
      run: docker image push --all-tags andrestless/dummy-web-app
